### ISSUE TITLE
Credits misplaced

### ISSUE THREAD

**Issue by Mannivu** [michaldrabik/Showly#884]
**Describe the bug**
When an actor is also part of the troupe of a movie, it isn't shown as an actor, but there's a double entry in the troupe line.

**Expected behavior**
Show both actor and troupe role.

**Screenshots**
In this example, Leigh Whannell is actor and screenwriter but he is listed twice under the "Screenrighter" role. Tapping on the first entry it shows his role, the second one has no role.
![Screenshot_2024-11-02-21-03-57-018_com michaldrabik showly2](https://github.com/user-attachments/assets/9b421826-2891-4586-b644-bf8511b57c4e)
![Screenshot_2024-11-02-21-04-00-495_com michaldrabik showly2](https://github.com/user-attachments/assets/48558919-d02d-4a75-8aa8-e75ed1192049)
![Screenshot_2024-11-02-21-07-37-963_com michaldrabik showly2](https://github.com/user-attachments/assets/0ef75e63-4fd2-40c5-b95e-c0cde6f19eef)
![Screenshot_2024-11-02-21-07-40-401_com michaldrabik showly2](https://github.com/user-attachments/assets/2c73786a-b9c3-48ba-a60f-6b46626ca66a)

**Comment by michaldrabik** [comment]
Fixed and pending for release.
