### ISSUE TITLE
[Bug] Revealing hidden plot shows the English one

### ISSUE THREAD

**Issue by Mannivu** [michaldrabik/showly#889]
**Describe the bug**
Having the "Hide episode plot" and "Tap to reveal hidden details" settings activated shows the plot in English, even if there's a translated plot on TMDB.

**Expected behavior**
Tapping on the hidden plot should show the translated version

**Screenshots**

**Hidden**
![Screenshot_2024-11-10-09-24-27-516_com michaldrabik showly2](https://github.com/user-attachments/assets/82d326fb-3012-4c51-847e-e7047ff61b74)

**Tapped**
![Screenshot_2024-11-10-09-24-22-683_com michaldrabik showly2](https://github.com/user-attachments/assets/c78c3c3a-f85f-4a9b-8973-0dc7b5d0cc80)

**After viewing episode**
![Screenshot_2024-11-10-09-24-53-795_com michaldrabik showly2](https://github.com/user-attachments/assets/f19dc3f4-e873-4f73-86ad-e53da750c425)

**Comment by michaldrabik** [comment]
Good find, will be checking.

**Comment by michaldrabik** [comment]
Note: seems like same thing for episode titles

**Comment by Mannivu** [comment]
> Note: seems like same thing for episode titles

I can confirm it happens also for titles.
