### ISSUE TITLE
Incorrect sync notifications with Trakt.tv during bulk additions

### ISSUE THREAD

**Issue by Treveo** [michaldrabik/showly#894]
**Description:**
When adding multiple items (e.g., shows or movies) in quick succession, the app occasionally displays incorrect sync error notifications. Despite these notifications, all data appears to sync correctly with Trakt.tv, and no information is lost.

**Steps to reproduce:**
Add multiple shows/movies in quick succession in Showly.
Repeat the process until an incorrect sync error notification appears.

**Expected behavior:**
No sync error notifications should appear if all data is syncing correctly.

**Actual behavior:**
The app displays a sync error notification, even though all data is successfully synced to Trakt.tv.

**Additional information:**
I think this issue is purely cosmetic, as the sync ultimately completes successfully, as far I could check it in Trakt.tv. However, the misleading error messages can cause unnecessary confusion for users.

![Screenshot_20241118_071807_Showly](https://github.com/user-attachments/assets/4ca6bdeb-3c0d-4ee3-ba8b-e40c5fcc6626)

**Comment by michaldrabik** [comment]
>  Add multiple shows/movies in quick succession in Showly.

Can you describe what exactly it means. Like what exactly is being tapped etc? May be helpful.

Can you also tell me how many custom lists do you have and if there is a chance that it is close to Trakt account limit (if it is not VIP)?

**Comment by Kelvino9** [comment]
I get the same error message every time since a week or two eventhough the synchronizations are happening correctly.

**Comment by Treveo** [comment]
@michaldrabik I also can confirm that this is working good for me, at least I don't get any error anymore. What about you, @Kelvino9?

**Comment by michaldrabik** [comment]
> Still getting the same error after each successful sync. I will try uninstalling and setting up everything again. Maybe that solves it.

Just to be sure. Only Github version was released. PlayStore is still being processed. Just in case you are a PlayStore user.

**Comment by Kelvino9** [comment]
No, I'm using the Github version through Obtainium.

**Comment by michaldrabik** [comment]
Ok, just double checking if you have **3.41.0** version actually. The repository name changed from "showly-2" to "showly" and was not sure if Obtanium picked it up for you.

**Comment by michaldrabik** [comment]
K. I'll close this issue as the OPs issue us fixed but If you start getting it again feel free to open another one.

**Comment by Kelvino9** [comment]
Everything seems alright now. Not a single error when synching. Thanks for your continues work on Showly.
