### ISSUE TITLE
[Feature Request] Don't require time when choosing 'Select Date' option

### ISSUE THREAD

**Issue by l0f3n** [michaldrabik/showly#903]
This adds a lot of unnecessary clicks when going through and adding a lot of previously watched movies. Also, you probably don't remember the exact time anyway, or care about it for that matter. Just set a default time at 20:00 or something in this case. It could be an option in the menu, if some people want to keep the current behaviour.

**Comment by michaldrabik** [comment]
You can already choose in Settings if you prefer the Select Date dialog or stick to always now.

**Comment by l0f3n** [comment]
Yeah, but when just getting on the app and adding movies I watched this year, I want to add a date without specifying the exact time.

**Comment by michaldrabik** [comment]
To be honest I feel like its a bit specific feature for additional settings etc. In case time is not an interest for you its just one more OK click and time is done to current one.

**Comment by l0f3n** [comment]
Okay sure. I feel like most people dont really care to record the exact time of day they watched a movie, but maybe im the odd one out here. And for the people that do, its better for them to have this feature than for it not to be there. I concede.

**Comment by michaldrabik** [comment]
> Okay sure. I feel like most people dont really care to record the exact time of day they watched a movie

You'd be surprised. Anyway its always a compromise of keeping app easy to use and functional. If you remove time setting for example then you start getting an emails about... setting exact time and vice versa ;)
