### ISSUE TITLE
[Ui bug] show details > episode list..   last item is behind  android buttonss...  Add  space to bottom please..

### ISSUE THREAD

**Issue by blackholeearth** [michaldrabik/showly#907]
**Describe the bug**
Ui bug .. show details > episode list..   last item is behind  android buttonss...  Add  spacer to bottom please..  100dp

**Expected behavior**
Last item should not be below android button bar

**Screenshots**

If![Screenshot_20241216_010210_Showly](https://github.com/user-attachments/assets/6f12b547-37be-4d9b-adae-31951dfd5c5c)

**Comment by michaldrabik** [comment]
Its already fixed in 3.41.0.
Where are you downloading the app from?

**Comment by blackholeearth** [comment]
now it installed thanks... 👏
it  INSTALLS , WORKS - MY MİSTAKE...   -- SOLVED..

**long:**

the previous version was 3.40.1 . and  it wasnt installing. showing install error.
i assumed  "it wont install" , because number looks similar,   3.40.1  vs "3.41.0"   .  numbers confused me.. .


have a healty , peaceful, and nice day...
hope to see you on good occasions.
